### ISSUE TITLE
Needs updates for new HandyNotes

### ISSUE THREAD

**Issue by Stanzilla** [EthanCentaurai/HandyNotes_LunarFestival#5]
Currently all nodes disappear from the map when you loot an elder in that zone

**Comment by EthanCentaurai** [comment]
Already fixed it. You have an out of date version installed.

**Comment by Stanzilla** [comment]
I'm on 1.6 :(

**Comment by Stanzilla** [comment]
Example: I just looted Sandrene in Sholazar and Wanikya despawned.

**Comment by EthanCentaurai** [comment]
Is the CurseForge packager dead again?

**Comment by Stanzilla** [comment]
No, I just had it set to release, not alpha, will try with alpha

**Comment by EthanCentaurai** [comment]
I pushed a new Release a while ago. It should be there by now.

**Comment by Stanzilla** [comment]
https://www.wowace.com/projects/handynotes_lunarfestival/files the last release is 1.6

**Comment by EthanCentaurai** [comment]
1.6.1 is still Processing. *sigh*

**Comment by Stanzilla** [comment]
Also it will take around an hour until everyone sees it in the Twitch app because their cache sucks

**Comment by Stanzilla** [comment]
Works with the alphas :)

**Comment by EthanCentaurai** [comment]
Awesomesauce! And the Release is approved now too. Isn't it great how a spelling mistake can cause so much damage? 😛
