### ISSUE TITLE
All nodes disappear from the map although the event is still going

### ISSUE THREAD

**Issue by dartraiden** [EthanCentaurai/HandyNotes_LunarFestival#6]
Server time is 9:19
![sekh4mbe14](https://user-images.githubusercontent.com/5046855/52551807-15577e80-2def-11e9-8813-7d2449649354.jpg)

Event ends at 10:00
![u11m7ui0cw](https://user-images.githubusercontent.com/5046855/52551837-2902e500-2def-11e9-85fe-0f8294074084.jpg)

All elders still available ingame, but addon does not show nodes on map.

**Comment by EthanCentaurai** [comment]
This is not something that can be fixed. All attempts to do so have only made things worse elsewhere.
